// @ts-check
// Az oldalsáv automatikusan a docs/ mappa szerkezetéből épül fel.
// Sorrend: a fájlok elején lévő `sidebar_position` határozza meg.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
